### ISSUE TITLE
Finding the signed header

### ISSUE THREAD

**Issue by jjf21** [ps1dr3x/greenpass-generator#1] opened 2021-07-13 08:54 UTC
Hi,

I'm trying to use your generator but I can't create a valid one.
I thing that 

> using an already signed header from a real certificate adds info on the issuer in the checker apps

is why it's not working. How did you extract this ?

I am able to get the header
```
Header
----------------
{1: -7, 4: b'|b\xee\xbe\x0e\....'}
```

and the signature of a QR

```
Signature ?
----------------
b"\x0b..WJ\xc7\x1f\x9e\xb9\xdfy\x88\x92\x......."
```

Thanks

**Comment by ps1dr3x** [comment] 2021-07-13 23:11
Hi,

I posted this code just for education purposes (it was described on a LinkedIn post), it can create plausible QRs in the (mostly) right format which are parsed correctly by the checker apps (at least the ones I tried) but obviously unless the private key of a state is leaked, no one (but who has a recognized key) will never be able to generate a valid signature. You can see also in the example image in the readme that the signature is marked as invalid.

Leaving the constant the comment is referring to empty should anyway generate a plausible QR, but with an additional "unknown issuer" message, or without info about the issuer (at least in some apps).

I just wrote that comment due to the fact that I noticed some checker apps shows more data (the description of the issuer) in the result page if they recognize the issuer from the signed header (for example in the context of a QR generated by this script, reusing a signed header from a valid certificate) but the overall signature check would still fail.

Anyway, you can get that header from a valid QR for example with the following code (header_1):

```python
    qr_file = "./qr.jpeg"
    image = cv2.imread(qr_file)
    qr_decoded = decode(image)
    qr_decoded_data = qr_decoded[0].data[4:]
    qr_decompressed_data = decompress(b45decode(qr_decoded_data))
    (_, (header_1, header_2, cbor_payload, sign)
     ) = flynn_decoder.loads(qr_decompressed_data)
```

**Comment by fedelake** [comment] 2021-07-27 05:46
hi, when i run the code, i get this error:
    qr_decoded = decode(image)
NameError: name 'decode' is not defined
why?

**Comment by fedelake** [comment] 2021-07-28 06:07
> Hi,
> 
> I'm trying to use your generator but I can't create a valid one.
> I thing that
> 
> > using an already signed header from a real certificate adds info on the issuer in the checker apps
> 
> is why it's not working. How did you extract this ?
> 
> I am able to get the header
> 
> ```
> Header
> ----------------
> {1: -7, 4: b'|b\xee\xbe\x0e\....'}
> ```
> 
> and the signature of a QR
> 
> ```
> Signature ?
> ----------------
> b"\x0b..WJ\xc7\x1f\x9e\xb9\xdfy\x88\x92\x......."
> ```
> 
> Thanks

Yeah, but the problem is the random private key...
How could i get the true private key?

**Comment by jjf21** [comment] 2021-07-28 06:15
Ask EU their private key 😂 
if you find it let me know.

**Comment by fedelake** [comment] 2021-07-28 06:46
> Ask EU their private key 😂
> if you find it let me know.

I got the sql file.

**Comment by Alex2113** [comment] 2021-07-28 07:41
Sorry but encryption is quite a new world from me, so even if I'm using a phdr and a valid signature there is no way to change the payload?

**Comment by ps1dr3x** [comment] 2021-07-29 08:15
No, the payload is signed and can't be tampered

**Comment by fedelake** [comment] 2021-07-29 08:41
A question: I have decoded a QR generated with the original data of a valid pass.
but I get an error like "no tag found".
Shouldn't at least the personal data appear?

**Comment by gabbys32** [comment] 2021-08-03 12:36
hi, one question why don't generate nothing?

**Comment by jjf21** [comment] 2021-08-03 12:47
I found that this is not encoding exactly the same way as a EU (french) HC1 qr code.

**Comment by flixst** [comment] 2021-08-17 14:37
> > Ask EU their private key 😂
> > if you find it let me know.
> 
> I got the sql file.

@fedelake what sql file?

**Comment by rapbando** [comment] 2021-09-15 15:33
> I found that this is not encoding exactly the same way as a EU (french) HC1 qr code.

This EU [document](https://ec.europa.eu/health/sites/default/files/ehealth/docs/vaccination-proof_interoperability-guidelines_en.pdf) explains the 3 different options. For example Italy uses option 2.

**Comment by lorreeg67** [comment] 2021-10-30 14:44
> > Chiedi a EU la loro chiave privata ? se lo trovi fammi sapere
> 
> Contattami, credo di avere una chiave privata che potrebbe funzionare. L'ho ricevuto ieri su Telegram.

PUOI DARLA?

**Comment by marco9060** [comment] 2021-11-01 01:51
Can you help me?

**Closed** 2021-11-01 02:14 UTC
